name: 🐍 QA Automation - Python a Jira Xray

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests-python:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v4

      # 2. Configurar Python
      - name: ⚙️ Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instalar dependencias Python
      - name: 📦 Instalar dependencias Python
        run: pip install -r requirements.txt

      # 4. Ejecutar pruebas Python (genera results_python.xml y reporte_python.html)
      - name: 🚀 Ejecutar pruebas Python
        run: pytest tests/test_*.py --junitxml=results_python.xml --html=reporte_python.html --self-contained-html

      # 4.5 Subir reporte HTML de pruebas Python (incluso si fallan)
      - name: 📤 Subir Reporte HTML de Pruebas Python
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-pruebas-python
          path: reporte_python.html

      # 5. Subir resultados a Jira Xray de forma automatica
      - name: 📤 Importar resultados a Jira Xray
        if: always()
        uses: mikepenz/xray-action@v3.0.5
        with:
          username: ${{ secrets.XRAY_CLIENT_ID }}
          password: ${{ secrets.XRAY_CLIENT_SECRET }}
          testFormat: "junit"
          testPaths: "results_python.xml"
          xrayCloud: "true"
          projectKey: "SCRUM"
